=== sys-bio/SED2/specsheets/core/SEDDocument/v1.0.0/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://sed-ml.org/schemas/core/SEDDocument/v1.0.0/schema.json",
  "title": "SED2 SEDDocument",
  "$defs": {
    "SEDDocument": {
      "type": "object",
      "allOf": [
        {
          "$ref": "../../../core/SEDBase/v1.0.0/schema.json#/$defs/SEDBaseFields"
        }
      ],
      "properties": {
        "version": {
          "type": "string",
          "pattern": "^v\\d+\\.\\d+\\.\\d+$",
          "x-rule-id": [
            "SEDDocument-0002",
            "SEDDocument-0003"
          ]
        },
        "constants": {
          "description": "Predefined constants. Keys are SIds; values may be any JSON value.",
          "type": "object",
          "propertyNames": {
            "$ref": "../../../core/Types/v1.0.0/schema.json#/$defs/SId"
          },
          "additionalProperties": {
            "$ref": "../../../core/Types/v1.0.0/schema.json#/$defs/AnyValueOrRef"
          },
          "x-rule-id": "SEDDocument-0005"
        },
        "tasks": {
          "description": "Tasks describe how to do things (simulations, calculations, imports, conversions, etc.).",
          "type": "object",
          "propertyNames": {
            "$ref": "../../../core/Types/v1.0.0/schema.json#/$defs/SId"
          },
          "additionalProperties": {
            "$ref": "../../../tasks/AbstractTask/v1.0.0/schema.json#/$defs/AbstractTask"
          },
          "x-rule-id": "SEDDocument-0006"
        },
        "outputs": {
          "description": "Outputs describe how to package results (reports, plots).",
          "type": "object",
          "propertyNames": {
            "$ref": "../../../core/Types/v1.0.0/schema.json#/$defs/SId"
          },
          "additionalProperties": {
            "$ref": "../../../outputs/AbstractOutput/v1.0.0/schema.json#/$defs/AbstractOutput"
          },
          "x-rule-id": "SEDDocument-0007"
        },
        "styles": {
          "description": "Styles used by plots. Permissive placeholder; the formal Style spec is TBD.",
          "type": "object",
          "propertyNames": {
            "$ref": "../../../core/Types/v1.0.0/schema.json#/$defs/SId"
          },
          "additionalProperties": {
            "$ref": "../../../core/Style/v1.0.0/schema.json#/$defs/Style"
          },
          "x-rule-id": "SEDDocument-0008"
        }
      },
      "required": [
        "version"
      ],
      "x-required-rule-ids": {
        "version": "SEDDocument-0001"
      },
      "unevaluatedProperties": false
    }
  },
  "$ref": "#/$defs/SEDDocument"
}

=== sys-bio/SED2/fixtures/generated/ref-type/Curve-0003-pass-00-correct-type-sim-fed.sed2.json
{
  "version": "v1.0.0",
  "constants": {
    "mybool": true,
    "mynumber": 1.3,
    "myint": 5,
    "myzero": 0,
    "mynegint": -1,
    "mystring": "hello",
    "myNumberArray": [
      1.2,
      2,
      6.6
    ],
    "myStringArray": [
      "how",
      "are",
      "you?"
    ],
    "myobject": {
      "a": 1,
      "b": 2
    },
    "myStringObject": {
      "a": "x",
      "b": "y"
    },
    "myenum": "points"
  },
  "tasks": {
    "model1": {
      "_type": "modelImport",
      "location": "filename.xml",
      "language": "urn:sedml:language:sbml"
    },
    "sim1": {
      "_type": "explicitODESimulation",
      "independentVariableRange": {
        "_type": "numericRange"
      },
      "model": "#tasks:model1.model",
      "independentVariable": "x",
      "outputVariables": []
    }
  },
  "outputs": {
    "x2": {
      "_type": "plot2D",
      "curves": {
        "x1": {
          "_type": "curve",
          "curveType": "#constants:myenum",
          "y": "#tasks:sim1",
          "x": "#tasks:sim1"
        }
      }
    }
  }
}

=== sys-bio/SED2/fixtures/generated/ref-type/SEDBase-0017-pass-00-Curve-xErrorLower-string-constant.sed2.json
{
  "version": "v1.0.0",
  "constants": {
    "mybool": true,
    "mynumber": 1.3,
    "myint": 5,
    "myzero": 0,
    "mynegint": -1,
    "mystring": "hello",
    "myNumberArray": [
      1.2,
      2,
      6.6
    ],
    "myStringArray": [
      "how",
      "are",
      "you?"
    ],
    "myobject": {
      "a": 1,
      "b": 2
    },
    "myStringObject": {
      "a": "x",
      "b": "y"
    }
  },
  "tasks": {
    "model1": {
      "_type": "modelImport",
      "location": "filename.xml",
      "language": "urn:sedml:language:sbml"
    }
  },
  "outputs": {
    "x2": {
      "_type": "plot2D",
      "curves": {
        "x1": {
          "_type": "curve",
          "curveType": "points",
          "y": "#constants:myNumberArray",
          "x": "#constants:myNumberArray",
          "xErrorLower": "#constants:mystring"
        }
      }
    }
  }
}

=== sys-bio/SED2/fixtures/generated/ref-type/Axis-0002-pass-00-correct-type-sim-fed.sed2.json
{
  "version": "v1.0.0",
  "constants": {
    "mybool": true,
    "mynumber": 1.3,
    "myint": 5,
    "myzero": 0,
    "mynegint": -1,
    "mystring": "hello",
    "myNumberArray": [
      1.2,
      2,
      6.6
    ],
    "myStringArray": [
      "how",
      "are",
      "you?"
    ],
    "myobject": {
      "a": 1,
      "b": 2
    },
    "myStringObject": {
      "a": "x",
      "b": "y"
    },
    "myenum": "linear"
  },
  "tasks": {
    "model1": {
      "_type": "modelImport",
      "location": "filename.xml",
      "language": "urn:sedml:language:sbml"
    },
    "sim1": {
      "_type": "explicitODESimulation",
      "independentVariableRange": {
        "_type": "numericRange"
      },
      "model": "#tasks:model1.model",
      "independentVariable": "x",
      "outputVariables": []
    }
  },
  "outputs": {
    "x1": {
      "_type": "plot2D",
      "curves": {
        "e1": {
          "_type": "curve",
          "curveType": "points",
          "y": "#tasks:sim1",
          "x": "#tasks:sim1"
        }
      },
      "rightYAxis": {
        "scale": "#constants:myenum"
      }
    }
  }
}

=== sys-bio/SED2/fixtures/generated/ref-type/Surface-0003-pass-00-correct-type.sed2.json
{
  "version": "v1.0.0",
  "constants": {
    "mybool": true,
    "mynumber": 1.3,
    "myint": 5,
    "myzero": 0,
    "mynegint": -1,
    "mystring": "hello",
    "myNumberArray": [
      1.2,
      2,
      6.6
    ],
    "myStringArray": [
      "how",
      "are",
      "you?"
    ],
    "myobject": {
      "a": 1,
      "b": 2
    },
    "myStringObject": {
      "a": "x",
      "b": "y"
    },
    "myenum": "parametricCurve"
  },
  "tasks": {
    "model1": {
      "_type": "modelImport",
      "location": "filename.xml",
      "language": "urn:sedml:language:sbml"
    }
  },
  "outputs": {
    "x2": {
      "_type": "plot3D",
      "surfaces": {
        "x1": {
          "surfaceType": "#constants:myenum",
          "x": "#constants:myNumberArray",
          "y": "#constants:myNumberArray",
          "z": "#constants:myNumberArray"
        }
      }
    }
  }
}

=== sys-bio/SED2/fixtures/generated/ref-type/SEDBase-0017-pass-00-Surface-z-number-constant.sed2.json
{
  "version": "v1.0.0",
  "constants": {
    "mybool": true,
    "mynumber": 1.3,
    "myint": 5,
    "myzero": 0,
    "mynegint": -1,
    "mystring": "hello",
    "myNumberArray": [
      1.2,
      2,
      6.6
    ],
    "myStringArray": [
      "how",
      "are",
      "you?"
    ],
    "myobject": {
      "a": 1,
      "b": 2
    },
    "myStringObject": {
      "a": "x",
      "b": "y"
    }
  },
  "tasks": {
    "model1": {
      "_type": "modelImport",
      "location": "filename.xml",
      "language": "urn:sedml:language:sbml"
    }
  },
  "outputs": {
    "x2": {
      "_type": "plot3D",
      "surfaces": {
        "x1": {
          "surfaceType": "parametricCurve",
          "x": "#constants:myNumberArray",
          "y": "#constants:myNumberArray",
          "z": "#constants:mynumber"
        }
      }
    }
  }
}

=== sys-bio/SED2/fixtures/generated/ref-type/Curve-0003-pass-00-correct-type.sed2.json
{
  "version": "v1.0.0",
  "constants": {
    "mybool": true,
    "mynumber": 1.3,
    "myint": 5,
    "myzero": 0,
    "mynegint": -1,
    "mystring": "hello",
    "myNumberArray": [
      1.2,
      2,
      6.6
    ],
    "myStringArray": [
      "how",
      "are",
      "you?"
    ],
    "myobject": {
      "a": 1,
      "b": 2
    },
    "myStringObject": {
      "a": "x",
      "b": "y"
    },
    "myenum": "points"
  },
  "tasks": {
    "model1": {
      "_type": "modelImport",
      "location": "filename.xml",
      "language": "urn:sedml:language:sbml"
    }
  },
  "outputs": {
    "x2": {
      "_type": "plot2D",
      "curves": {
        "x1": {
          "_type": "curve",
          "curveType": "#constants:myenum",
          "y": "#constants:myNumberArray",
          "x": "#constants:myNumberArray"
        }
      }
    }
  }
}

=== sys-bio/SED2/fixtures/handwritten/SEDBase-0007-pass-00-output-references-task.sed2.json
{
  "version": "v1.0.0",
  "constants": {
    "k_num": 1.5,
    "k_strings": [
      "a",
      "b"
    ],
    "k_array": [
      10,
      20,
      30
    ],
    "k_obj": {
      "a": 1,
      "b": 2
    },
    "k_str": "hello"
  },
  "tasks": {
    "m1": {
      "_type": "modelImport",
      "location": "model.xml",
      "language": "urn:sedml:language:sbml"
    },
    "sim1": {
      "_type": "explicitODESimulation",
      "model": "#tasks:m1.model",
      "independentVariable": "time",
      "outputVariables": [
        "S1",
        "S2"
      ],
      "independentVariableRange": {
        "_type": "numericRange",
        "values": [
          0,
          1,
          2,
          3
        ]
      }
    }
  },
  "outputs": {
    "rep1": {
      "_type": "report",
      "data": "#tasks:sim1"
    }
  }
}

=== sys-bio/SED2/fixtures/generated/ref-type/SEDBase-0017-pass-00-Curve-yFrom-data-output.sed2.json
{
  "version": "v1.0.0",
  "constants": {
    "mybool": true,
    "mynumber": 1.3,
    "myint": 5,
    "myzero": 0,
    "mynegint": -1,
    "mystring": "hello",
    "myNumberArray": [
      1.2,
      2,
      6.6
    ],
    "myStringArray": [
      "how",
      "are",
      "you?"
    ],
    "myobject": {
      "a": 1,
      "b": 2
    },
    "myStringObject": {
      "a": "x",
      "b": "y"
    }
  },
  "tasks": {
    "model1": {
      "_type": "modelImport",
      "location": "filename.xml",
      "language": "urn:sedml:language:sbml"
    },
    "sim1": {
      "_type": "explicitODESimulation",
      "independentVariableRange": {
        "_type": "numericRange"
      },
      "model": "#tasks:model1.model",
      "independentVariable": "x",
      "outputVariables": []
    }
  },
  "outputs": {
    "x2": {
      "_type": "plot2D",
      "curves": {
        "x1": {
          "_type": "curve",
          "curveType": "points",
          "y": "#constants:myNumberArray",
          "x": "#constants:myNumberArray",
          "yFrom": "#tasks:sim1"
        }
      }
    }
  }
}
